### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x88 in position 45953: character maps to <undefined>

### ISSUE THREAD

**Issue by dragancevs** [louisabraham/har2requests#1]
Hello, i'm not able to convert har file to python script.
It writes to me this message:
 File "c:\users\stefan\appdata\local\programs\python\python37\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x88 in position 45953: character maps to <undefined>

How can i fix this?

**Comment by louisabraham** [comment]
Hi, I didn't even know people were using this :)

Can you do the following steps in order?

- Post the full traceback
-  Post the output of this command:

```
python3 -c "import locale; print(locale.getpreferredencoding(False))"
```

- If you know how to do it, modify the code https://github.com/louisabraham/har2requests/blob/master/har2requests/__init__.py#L167 with this line:

```python
@click.argument("src", type=click.File(encoding="utf-8"))
```

and test again

**Comment by dragancevs** [comment]
> C:\Users\Stefan>har2requests input_booking.har > output.py
Traceback (most recent call last):
  File "c:\users\stefan\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\stefan\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Stefan\AppData\Local\Programs\Python\Python37\Scripts\har2requests.exe\__main__.py", line 9, in <module>
  File "c:\users\stefan\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\stefan\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\stefan\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\stefan\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\stefan\appdata\local\programs\python\python37\lib\site-packages\har2requests\__init__.py", line 169, in main
    entries = json.load(src)["log"]["entries"]
  File "c:\users\stefan\appdata\local\programs\python\python37\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "c:\users\stefan\appdata\local\programs\python\python37\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 352847: character maps to <undefined>

The output of the command (python3 -c "import locale; print(locale.getpreferredencoding(False))") is

> cp1250

When i have changed the line in the __init__.py
It showed me this:

> C:\Users\Stefan>har2requests input_booking.har > output_booking.py
Traceback (most recent call last):
  File "c:\users\stefan\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\stefan\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Stefan\AppData\Local\Programs\Python\Python37\Scripts\har2requests.exe\__main__.py", line 9, in <module>
  File "c:\users\stefan\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\stefan\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\stefan\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\stefan\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\stefan\appdata\local\programs\python\python37\lib\site-packages\har2requests\__init__.py", line 177, in main
    entry["request"], entry["response"], entry["startedDateTime"]
  File "c:\users\stefan\appdata\local\programs\python\python37\lib\site-packages\har2requests\__init__.py", line 67, in from_json
    responseText=response["content"]["text"],
KeyError: 'text'

Thank you for your help, i really appreciate it.

**Comment by louisabraham** [comment]
Hi, it seems that the encoding was the main issue since after the fix the bug shows at another place.

I made the encoding change in the last version (0.4.4). Thanks for your contribution!

Regarding the new bug, I'll open a new issue.
