### ISSUE TITLE
POST text field parsing results in "TypeError: string indices must be integers"

### ISSUE THREAD

**Issue by blu3r4y** [louisabraham/har2requests#10]
When parsing a HAR file that uses the `text` field for the `postData`, the parser fails with a `TypeError`

```
Traceback (most recent call last):
  File "C:\tools\Anaconda3\envs\scratch37\Scripts\har2requests-script.py", line 11, in <module>
    load_entry_point('har2requests', 'console_scripts', 'har2requests')()
  File "C:\tools\Anaconda3\envs\scratch37\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\tools\Anaconda3\envs\scratch37\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\tools\Anaconda3\envs\scratch37\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\tools\Anaconda3\envs\scratch37\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\data\dropbox\src\har2requests\har2requests\__init__.py", line 197, in main
    entry["request"], entry["response"], entry["startedDateTime"]
  File "c:\data\dropbox\src\har2requests\har2requests\__init__.py", line 69, in from_json
    postData = Request.dict_from_har(pd["text"])
  File "c:\data\dropbox\src\har2requests\har2requests\__init__.py", line 93, in dict_from_har
    return {x["name"]: x["value"] for x in j}
  File "c:\data\dropbox\src\har2requests\har2requests\__init__.py", line 93, in <dictcomp>
    return {x["name"]: x["value"] for x in j}
TypeError: string indices must be integers
```

Find a demo HAR file here: [control.stackpath.com.zip](https://github.com/louisabraham/har2requests/files/5361433/control.stackpath.com.zip)
The problematic section is:

```
"postData": {
	"mimeType": "application/json",
	"text": "{\"client_id\":\"cwTfvP1xlNFwN\",\"username\":\"mail\",\"password\":\"password\",\"realm\":\"Username-Password-Authentication\",\"credential_type\":\"http://auth0.com/oauth/grant-type/password-realm\"}"
}
```

**Comment by louisabraham** [comment]
This feature was already implemented on the unsafe branch.
https://github.com/louisabraham/har2requests/blob/0a81b3f9037bd1184c3c0f260cf8d2246ac72227/har2requests/__init__.py#L78

I'll soon merge it on master. If you agree I'll close this PR.

**Comment by blu3r4y** [comment]
@louisabraham Thanks, looks good, yeah, close it!

**Comment by louisabraham** [comment]
Thank you for providing a PR with the issue!
