### ISSUE TITLE
Error Message: TypeError: cannot use a bytes pattern on a string-like object

### ISSUE THREAD

**Issue by skirven4** [louisabraham/har2requests#18]
Hi! I'm trying to run this code on Python 3.8 on an Ubuntu box, and I'm getting this error. I tried creating the har in both Edge and Chrome and got the same error. I can see the output of the page before the error, so I know it's running.

```
Traceback (most recent call last):
  File "/home/stephen/.local/bin/har2requests", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/stephen/.local/lib/python3.8/site-packages/har2requests/__init__.py", line 132, in main
    request = Request.from_json(
  File "/home/stephen/.local/lib/python3.8/site-packages/har2requests/request.py", line 74, in from_json
    headers=Request.process_headers(Request.dict_from_har(request["headers"])),
  File "/home/stephen/.local/lib/python3.8/site-packages/har2requests/request.py", line 94, in process_headers
    headers = {k: v for k, v in headers.items() if is_legal_header_name(k)}
  File "/home/stephen/.local/lib/python3.8/site-packages/har2requests/request.py", line 94, in <dictcomp>
    headers = {k: v for k, v in headers.items() if is_legal_header_name(k)}
TypeError: cannot use a bytes pattern on a string-like object

```

**Comment by skirven4** [comment]
Closing this issue. I was able to use the latest version of Postman in order to open the HAR file, and it was able to then generate the cURL command I needed to extract the information I was after.
Thanks!

**Comment by louisabraham** [comment]
Great! Does it work with har2requests too? I think it should.

**Comment by skirven4** [comment]
It never did. I kept getting the error. My use case was trying to get the api to work, then run the data through Cribl Logstream, then to Splunk. I can get Logstream to run the api and parse what I need. Thanks!


Sent from Yahoo Mail for iPhone


On Saturday, February 19, 2022, 12:56 PM, Louis Abraham ***@***.***> wrote:




Great! Does it work with har2requests too? I think it should.

**Comment by louisabraham** [comment]
Well I fixed it on Wednesday so don't hesitate to try again

**Comment by skirven4** [comment]
Will do. I never saw a comment on it, but I’ll be happy to test again!


Sent from Yahoo Mail for iPhone


On Saturday, February 19, 2022, 1:56 PM, Louis Abraham ***@***.***> wrote:




Well I fixed it on Wednesday so don't hesitate to try again

**Comment by skirven4** [comment]
I just checked the code, and yes, it did run correctly for my API call. Thank you!

**Comment by louisabraham** [comment]
Great! Sorry I didn't fix it sooner
